# Generated by Django 4.0.5 on 2022-06-28 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_program_id_alter_response_id_alter_salad_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('persons', models.IntegerField()),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('image', models.ImageField(upload_to='events')),
                ('index', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('text1', models.CharField(max_length=50)),
                ('text2', models.CharField(max_length=50)),
                ('text3', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('img', models.ImageField(upload_to='foods')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
        migrations.DeleteModel(
            name='Starter',
        ),
        migrations.RemoveField(
            model_name='table',
            name='date',
        ),
        migrations.RemoveField(
            model_name='table',
            name='email',
        ),
        migrations.RemoveField(
            model_name='table',
            name='message',
        ),
        migrations.RemoveField(
            model_name='table',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='table',
            name='phone',
        ),
        migrations.AlterField(
            model_name='response',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='response',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='response',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='response',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='response',
            name='subjects',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='booktable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.table'),
        ),
    ]
